### ISSUE TITLE
Remove misuse of hr element from article pattern

### ISSUE THREAD

**Issue by scottaohara** [5t3ph/htmlrecipes#12]
[the article pattern](https://htmlrecipes.dev/#article) includes instances of the `hr` element prior to the `h3`s.

an `hr` represents a paragraph-level shift in topic, so it is both unnecessary and incorrect to use it prior to a heading, which already signifies a topic level change by implicitly defining a new section in the document outline.

Ideally this pattern would be instead using CSS to provide this visual flourish.

**Comment by 5t3ph** [comment]
@scottaohara thanks Scott, I've updated the example and added a note about this guidance.
