### ISSUE TITLE
Figure pattern missing alt description on image

### ISSUE THREAD

**Issue by scottaohara** [5t3ph/htmlrecipes#13]
if an image is the primary content of a `figure` then it needs to be given alternative text.  giving it an empty alt will not expose the graphic to AT, essentially creating a figure with a figcaption that captions 'nothing'.

Being this is an example of auto-generating dinosaur photos, maybe add an alt indicating that, or nondescript "alternative text goes here", or something like that?

**Comment by 5t3ph** [comment]
@scottaohara thanks, an update has been made and clarification added to the description.
